### ISSUE TITLE
2 Instances in Eureka server - One is my own local system. why?

### ISSUE THREAD

**Issue by ssiva89** [koushikkothagal/spring-boot-microservices-workshop#8]
Hi ,
i've registered the MovieInfoService as client in Eureka server. i get to see two instances and one of them is my own local system.
i want to know how the Eureka server is taking it as a client.?

![Eureka server - 2 instances](https://user-images.githubusercontent.com/7196796/95222380-0ddfb700-0816-11eb-9eb8-77196f895799.png)

**Comment by viktrine** [comment]
Hi, by default a Eureka server is a Eureka client. To avoid this, add the following to your property file :
```
#Registry settings
eureka:
  client:
    register-with-eureka: false
    fetch-registry: false
```
Thank you.
